name: SpectrumEngineCI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      # Runs a single command using the runners shell
      - name: Installing requirements
        run: ./install-requirements.sh

      # Runs a set of commands using the runners shell
      - name: Building...
        run: ./build-linux.sh
        
      - name: Finishing...
        run: echo Built!
